### DISCUSSION TITLE
cant access web ui since update 25.02.1

### DISCUSSION THREAD

**Discussion by Kamikaze01git** [jlesage/docker-video-duplicate-finder#15] [Q&A] [answered]
Hello.

I am sure it must be my fault... but i can not accress the web ui anymore.
I use compose
```
version: "3"
services:
  video-duplicate-finder:
    container_name: Video-Duplicate-Finder
    image: jlesage/video-duplicate-finder
    environment:
      USER_ID: <<PUID>>
      GROUP_ID: <<PGID>>
      TZ: <<MY-TZ>>
      DARK_MODE: 1
      WEB_AUTHENTICATION_USERNAME: <<MY-USER>>
      WEB_AUTHENTICATION_PASSWORD: <<MY-PASS>>
    ports:
      - 5801:5801
    volumes:
      - /volume2/docker/video-duplicate-finder:/config:rw
      - /volume2/docker/video-duplicate-finder/TRASH:/trash:rw
      - /volume1/photo:/photo:rw
      - /volume1/homes:/homes:rw
      - /volume1/BACKUPS:/BACKUPS:rw
    restart: unless-stopped
    networks:
      my-network:
        ipv4_address: 172.22.1.1

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/23
          ip_range: 172.22.1.0/31
          gateway: 172.22.0.1

      options:
        level: "0"
```

Container sucessfully created, but Brower only says "no answer from 192.168.x.x:5801"

Log
```
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-openbox.sh: executing...
[cont-init   ] 10-openbox.sh: terminated successfully.
[cont-init   ] 10-pkgs-mirror.sh: executing...
[cont-init   ] 10-pkgs-mirror.sh: terminated successfully.
[cont-init   ] 10-pulse.sh: executing...
[cont-init   ] 10-pulse.sh: terminated successfully.
[cont-init   ] 10-set-tmp-dir-perms.sh: executing...
[cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-webauth.sh: executing...
[cont-init   ] 10-webauth.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init   ] 15-cjk-font.sh: executing...
[cont-init   ] 15-cjk-font.sh: terminated successfully.
[cont-init   ] 15-install-pkgs.sh: executing...
[cont-init   ] 15-install-pkgs.sh: terminated successfully.
[cont-init   ] 55-vdf.sh: executing...
[cont-init   ] 55-vdf.sh: terminated successfully.
[cont-init   ] 85-take-config-ownership.sh: executing...
[cont-init   ] 85-take-config-ownership.sh: terminated successfully.
[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           Video Duplicate Finder                        │
    │ Application Version:   3.0.x-018ad52                                 │
    │ Docker Image Version:  25.02.1                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'audiorecorder'...
[supervisor  ] service 'audiorecorder' is disabled.
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'webauth'...
[supervisor  ] service 'webauth' is disabled.
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'pulseaudio'...
[supervisor  ] service 'pulseaudio' is disabled.
[supervisor  ] loading service 'xcompmgr'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] loading service 'logrotate'...
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.14.1 - built Feb  7 2025 21:11:51
[xvnc        ] Copyright (C) 1999-2024 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Tue Feb 11 14:02:06 2025
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'xcompmgr'...
[supervisor  ] starting service 'app'...
[supervisor  ] all services started.
```

The Problem is the same, even when i did not use any own network
```
version: "3"
services:
  video-duplicate-finder:
    container_name: Video-Duplicate-Finder
    image: jlesage/video-duplicate-finder
    environment:
      USER_ID: <<PUID>>
      GROUP_ID: <<PGID>>
      TZ: <<MY-TZ>>
      DARK_MODE: 1
      WEB_AUTHENTICATION_USERNAME: <<MY-USER>>
      WEB_AUTHENTICATION_PASSWORD: <<MY-PASS>>
    ports:
      - 5801:5801
    volumes:
      - /volume2/docker/video-duplicate-finder:/config:rw
      - /volume2/docker/video-duplicate-finder/TRASH:/trash:rw
      - /volume1/photo:/photo:rw
      - /volume1/homes:/homes:rw
      - /volume1/BACKUPS:/BACKUPS:rw
    restart: unless-stopped
```

Last time it worked was just 2 Weeks ago i think... so older versions should work, but i also tried
image: jlesage/video-duplicate-finder:v24.12.1
image: jlesage/video-duplicate-finder:v24.09.1
image: jlesage/video-duplicate-finder:v24.07.1
and still not working.

What is my mistake? I am pretty sure it's on my site, but I did not change anything...

I use Portainer Standalon 20.10.23 on a Synologs NAS DS920+
thx :)
