### ISSUE TITLE
[Bug] cannot set the similarity percentages to descendants.

### ISSUE THREAD

**Issue by Kamikaze01git** [jlesage/docker-video-duplicate-finder#13]
### Current Behavior

When i try to change the percentage, it always changes to a full number. But i need to change it to eg. 99,5% and not 99%

### Expected Behavior

Set the percentage to a more accurate number

### Steps To Reproduce

go to settings --> misc --> try to set percentage to eg. 99.5%

### Environment

Synology DS920+ with latest FW.

### Container creation

Installed via Portainer with following compose file:

```
version: "3"
services:
  video-duplicate-finder:
    container_name: video-duplicate-finder
    image: jlesage/video-duplicate-finder
    environment:
      USER_ID: MyUID
      GROUP_ID: MyGID
      TZ: Europe/Vienna
      DARK_MODE: 1
      WEB_AUTHENTICATION_USERNAME: MyUsername
      WEB_AUTHENTICATION_PASSWORD: MyUserpass
    ports:
      - 5800:5800
    volumes:
      - /volume2/docker/video-duplicate-finder:/config:rw
      - /volume2/docker/video-duplicate-finder/TRASH:/trash:rw
      - /volume1/photo:/photo:rw
```

### Container log

```text
no log after try to change the percentage. it just automatically switched to a full number.
When i put 99.5 ans push ENTER, it writes 99
```
